test = {   'name': 'q2_8',
    'points': None,
    'suites': [   {   'cases': [   {   'code': ">>> # Please actually go on Piazza and look at the threads.\n>>> # Looks like you didn't make a string.\n>>> type(secret) == str\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> len(secret) == len("thereisnosecret")\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
